version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

executors:
  default:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/my-app

commands:
  restore_yarn:
    steps:
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}-{{ .Branch }}

  save_yarn:
    steps:
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}-{{ .Branch }}
          paths:
            - ~/.cache/yarn

  restore_node:
    steps:
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}-{{ .Branch }}

  save_node:
    steps:
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}-{{ .Branch }}
          paths:
            - node_modules
  
  store_build_artifacts:
    steps:
      - store_artifacts:
          path: .next

jobs:
  node:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - restore_node
      - run: yarn
      - save_yarn
      - save_node

  deploy:
    parameters:
      env:
        type: enum
        enum: ["production", "staging"]
      aws-access-key-id:
        type: env_var_name
      aws-secret-access-key:
        type: env_var_name
      aws-region:
        type: env_var_name
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - restore_node
      - run: yarn
      - save_yarn
      - save_node
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: << parameters.aws-access-key-id >>
          aws-secret-access-key: << parameters.aws-secret-access-key >>
          aws-region: << parameters.aws-region >>
      # - run: yarn deploy:<< parameters.env >>
      # - store_build_artifacts

workflows:
  build_and_deploy:
    jobs:
      - node

      # staging
      - deploy: &deploy
          env: staging
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION

          requires:
            - node
          name: deploy_staging
          filters:
            branches:
              only: staging
            tags:
              ignore: /.*/
      
      # production
      - deploy:
          <<: *deploy

          env: production

          name: deploy_production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
